In [1]:
import numpy as np

In [3]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])

In [4]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [5]:
mean_a=np.mean(a,axis=0)

In [6]:
mean_a

array([2. , 8.4])

In [7]:
a_centered = a - mean_a

In [8]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [9]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]

In [10]:
a_centered_sp

8.0

In [11]:
a_centered_sp / (a_centered.shape[0] - 1)

2.0