In [10]:
import numpy as np

Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [2]:
ar1 = np.arange(12, 24)

print(ar1)

[12 13 14 15 16 17 18 19 20 21 22 23]


Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [4]:
a = ar1.reshape(3, 4)

print(a)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [6]:
a1 = ar1.reshape(2, 6)

print(a1)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [7]:
a2 = ar1.reshape(4, 3)

print(a2)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [12]:
a3 = ar1.reshape(12, 1)

print(a3)

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [9]:
a4 = ar1.reshape(6, 2)

print(a4)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [17]:
ar1.reshape(12, -1)


array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [18]:
ar1.reshape(2, -1)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [19]:
ar1.reshape(-1, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [20]:
ar1.reshape(-1, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [22]:
ar1.reshape(-1, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?


In [ ]:
#НЕТ

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [23]:
b = np.random.randn(3, 4)

print(b)

[[ 0.71610891 -1.80136443  1.34086492 -1.20960412]
 [ 0.62453593  1.38254125  0.61704706  1.29126857]
 [-0.43264236  1.01449514  2.84965204  2.47547579]]


In [24]:
c = b.flatten()

print(c)

[ 0.71610891 -1.80136443  1.34086492 -1.20960412  0.62453593  1.38254125
  0.61704706  1.29126857 -0.43264236  1.01449514  2.84965204  2.47547579]


Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.


In [33]:
a = np.arange(20, 0, -2)

print(a)

[20 18 16 14 12 10  8  6  4  2]


Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?


In [34]:
b = np.arange(20, 1, -2)

print(b)

[20 18 16 14 12 10  8  6  4  2]


In [ ]:
#разницы нет, т.к. шаг 2, то получиличь одинаковые массивы

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.


In [42]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
c = np.vstack((a, b))
print(c)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [43]:
c.size

10

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?


In [66]:
a = np.arange(0, 12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [55]:
A = a.reshape(4,3)
print(A)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [57]:
At = A.T
print(At)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [62]:
B = A.dot(At)
print(B)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [63]:
B.size

16

In [65]:
np.linalg.det(B)
#определитель матрицы равен 0, вычислить обратную матрицу нельзя

0.0

Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.


In [69]:
np.random.seed(42)

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 


In [71]:
c = np.random.randint(0, 16, (1, 16))
print(c)

[[ 6  3 12 14 10  7 12  4  6  9  2  6 10 10  7  4]]


Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.


In [72]:
C = c.reshape((4, 4))
print(C)

[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]


In [74]:
D = B*10 + C
print(D)

[[  56  143  242  334]
 [ 150  507  872 1224]
 [ 236  869 1492 2126]
 [ 330 1230 2127 3024]]


Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.


In [79]:
D_inv = np.linalg.inv(D)
print(D_inv)

[[ 0.135368   -0.09412681 -0.0250975   0.04079219]
 [-0.17297808  0.16351785  0.1740805  -0.16946638]
 [-0.05802224  0.09496052 -0.10651536  0.04285695]
 [ 0.09639712 -0.12303113  0.00685229  0.03466452]]


In [83]:
c = np.zeros_like(D_inv)
c[D_inv>0] = 1
D_inv = c
print(D_inv)

[[1. 0. 0. 1.]
 [0. 1. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 1.]]


In [84]:
E = np.where(D_inv, B, C)
print(E)

[[  5   3  12  32]
 [ 10  50  86   4]
 [  6  86   2 212]
 [ 32  10 212 302]]
